---
- name: create group
  group:
    name: panda
    state: present

- name: create user
  user:
    name: panda
    shell: /usr/bin/bash
    groups:
      - panda
      - sudo

- name: copy authorized_key
  authorized_key:
    user: panda
    state: present
    key: "{{ lookup('file', '/home/vagrant/.ssh/authorized_keys') }}"
